[package]
name = "mute-unmute-poc-proto"
version = "0.1.0"
authors = ["Semen Evdokimov <evdokimovs@protonmail.ch>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
